services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    command: sh -c "rabbitmq-plugins enable rabbitmq_management && rabbitmq-server"
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  notification-worker:
    build:
      context: .
      dockerfile: backend/workers/Dockerfile
    container_name: notification-worker
    restart: always
    depends_on:
      - rabbitmq
      - redis
    env_file:
      - .env
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL_DOCKER}
      REDIS_URL: ${REDIS_URL_DOCKER}

volumes:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local
